server:
  port: 8090
spring:
  thymeleaf:
    cache: false
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: update
  h2:
    console.enabled: true
    console.path: /h2
  datasource:
    url: jdbc:h2:./data3
    username: group44
    password: 123456
    driver-class-name: org.h2.Driver
  flyway:
    enabled: false


