
spring:
  thymeleaf:
    cache: false
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: update
  h2:
    console.enabled: true
    console.path: /h2
  datasource:
    url: jdbc:h2:./data8
    username: jack
    password: csc207
    driver-class-name: org.h2.Driver
  flyway:
    enabled: true

  security:
    user:
      name: group44
      password: csc207
server:
  port: 8080

